//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EEM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_greendot {
            get {
                object obj = ResourceManager.GetObject("icon_greendot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_reddot {
            get {
                object obj = ResourceManager.GetObject("icon_reddot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_yellowdot {
            get {
                object obj = ResourceManager.GetObject("icon_yellowdot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon King {
            get {
                object obj = ResourceManager.GetObject("King", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:.
        /// </summary>
        internal static string MainScreen__loUAdapter_OnAuthenticationFailed_Error {
            get {
                return ResourceManager.GetString("MainScreen__loUAdapter_OnAuthenticationFailed_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string MainScreen_Connect_Offline {
            get {
                return ResourceManager.GetString("MainScreen_Connect_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        internal static string MainScreen_Connect_Online {
            get {
                return ResourceManager.GetString("MainScreen_Connect_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging into LoU..
        /// </summary>
        internal static string MainScreen_connectToolStripMenuItem_Click_Logging_into_LoU {
            get {
                return ResourceManager.GetString("MainScreen_connectToolStripMenuItem_Click_Logging_into_LoU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed..
        /// </summary>
        internal static string MainScreen_connectToolStripMenuItem_Click_Login_Failed {
            get {
                return ResourceManager.GetString("MainScreen_connectToolStripMenuItem_Click_Login_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Closed.
        /// </summary>
        internal static string MainScreen_Disconnect_Connection_Closed {
            get {
                return ResourceManager.GetString("MainScreen_Disconnect_Connection_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes to game server settings require you to disconnect and reconnect..
        /// </summary>
        internal static string MainScreen_optionsToolStripMenuItem_Click_Changes_to_game_server_settings_require_you_to_disconnect_and_reconnect {
            get {
                return ResourceManager.GetString("MainScreen_optionsToolStripMenuItem_Click_Changes_to_game_server_settings_require" +
                        "_you_to_disconnect_and_reconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning:.
        /// </summary>
        internal static string MainScreen_optionsToolStripMenuItem_Click_Warning {
            get {
                return ResourceManager.GetString("MainScreen_optionsToolStripMenuItem_Click_Warning", resourceCulture);
            }
        }
    }
}
